[rtpengine]
interface = 139.64.178.194
listen-ng = 127.0.0.1:2223
port-min = 32768
port-max = 49151
log-level = 5
kernel-table = 0
foreground = false
log-stderr = false
pidfile = /run/rtpengine/rtpengine.pid
